### PR TITLE
Added missing migration file

### PR DESCRIPTION
**Pull request by stuartaccent**
Thanks :)

### CODE REVIEW

**Comment by ababic** [comment]
Thank you!

**Comment by stuartaccent** [comment]
Welcome, when do you plan on next releasing this as this is affecting the current live version on pypi. 

Cheers

**Comment by ababic** [comment]
@stuartaccent. I was planning to do a major release tomorrow, but there are still important things that I want to do before then, so that will have to wait. I'll cherry-pick this out to create a minor/bug-fix release within the next few days.

**Comment by stuartaccent** [comment]
ok, thanks @ababic

**Pull request merged**
