### PR TITLE
Templatetag Full URL Feature

### PR DESCRIPTION
**Pull request by trumpet2012**
This is a continuation of PR #144, with the commits squashed down to one.

**Feature**: Adding an optional `use_absolute_page_urls` argument to all menu tags that when `True`, will render page links using the full URL instead of the relative URL.

### CODE REVIEW

**Comment by ababic** [comment]
Hey @trumpet2012. How do you feel about changing `use_absolute_urls` throughout to `use_absolute_page_urls`? I know it's a tad longer, but I think it's a slightly better match for the effect is has.

**Comment by trumpet2012** [comment]
@ababic Yeah that better conveys what it is doing.

**Comment by ababic** [comment]
@trumpet2012 And we're merged! Thanks for getting involved :)

**Comment by trumpet2012** [comment]
@ababic Awesome! I'm happy to contribute. I appreciate you being so prompt and active in getting this done.

**Pull request merged**
