### PR TITLE
Remove six dependency

### LINKED ISSUE #354: Depricated Django package - from django.utils import six
As the title says. The new version of Django (3) no longer supports this module.

To fix the issue one has to change the line `from django.utils import six` in `menu.py` to `import six`.

You may have to install it with `pip install six` first.

### PR DESCRIPTION
**Pull request by ArkadiuszMichalRys**
Fixes #354 by removing the six import and use.
Should make wagtail 2.8 compatible (with django 3.0.x).

### CODE REVIEW

**Comment by ArkadiuszMichalRys** [comment]
I am not sure why that one check failed. It seems like it couldn't pull the source code from Github?

**Comment by jnsdrtlf** [comment]
I've been testing this locally and it works fine with Django 3. Could we submit a new, updated version including this commit to PyPI so that wagtailmenus if officially compatible with django 3? Or am I missing something?

**Comment by ababic** [comment]
Hi @jnsdrtlf. There are a few housekeeping bits that I need to take care of before I release another version. I can probably get away with doing a bug fix / patch release, as there haven't been any feature changes since the last minor release. Watch this space :)

**Comment by ababic** [comment]
3.0.1 has now been released. Thanks @jnsdrtlf!

**Comment by jnsdrtlf** [comment]
That was quick! Thanks for your work! 🎉

**Pull request merged**
