### PR TITLE
add lithuanian translations

### PR DESCRIPTION
**Pull request by treavis**
Would be nice to have this project in Transifex. Translations done wit Poedit.

### CODE REVIEW

**Comment by ababic** [comment]
Thanks @treavis. Honestly, I'm completely new to managing projects with translations, and never really understood how it works. I've just set up a project in Transifex, if you'd rather add them via that? https://www.transifex.com/rkhleics/wagtailmenus/

**Comment by ababic** [comment]
Hi @treavis. After setting up transifex, I did some reading up on best practice, and, with the aim of making things easier for translators in future, I've gone and implemented named parameters far more widely, and have also unmarked some of the wordy exception messages from utils.misc. 

I really appreciate the work you've put in here, but because of the changes I've implemented, a lot of message ids are now different / removed, and this PR is now a little bit out if date (sorry!). 

Are you okay to submit fresh translations? It's okay if not. What you've provided here is still useful... I will do what I can with it and get it pushed to Transifex myself, I'd you'd prefer?

Thank you again for your efforts and patience.

**Comment by treavis** [comment]
I will submit new translations, I just need you to add Lithuanian language in transifex project. I made a request for it.

Thanks for quick responses!

**Comment by ababic** [comment]
Hi @treavis, I have approved that request to support Lithuanian now. Thanks

**Pull request closed without merging**
