### PR TITLE
Added german translation

### PR DESCRIPTION
**Pull request by bloodywing**
Well I made a German translation. Review by other native speakers is welcome.

### CODE REVIEW

**Comment by bloodywing** [comment]
You might want to compile the po files to .mo and add them to the repository. Otherwise django will not use the translation.

in **MANIFEST.in**
`recursive-include wagtailmenus/locale *.mo`

**Comment by ababic** [comment]
Hey @bloodywing. Thank you for contributing :)

I'm honestly unsure about how the translations work, so I don't know about including the .mo files. If they were necessary, I would have thought another translator would have brought that up? I shall wait a while and see if anybody can clarify that.

Regarding the wagtail 1.8 support changes, I cannot accept those as part of this PR I'm afraid. I need to tackle that as a separate pull that also adds new .tox test environments for wagtail 1.8 and ensures that everything checks out. It wouldn't be right to announce support for 1.8 otherwise.

**Comment by bloodywing** [comment]
I saw this with the mo files in wagtails repository. And even the Django repository includes the compiled ones: https://github.com/django/django/tree/master/django/contrib/admin/locale/en_GB/LC_MESSAGES

I've already rewritten the tox.ini and the base/requirements.txt and currently running the tests local.

**Comment by ababic** [comment]
Thanks @bloodywing.

In that case, I'm happy for the `.mo` files to be included.

Also, please add yourself as a translator in `CONTRIBUTORS.md` :)

RE the 1.8 support. I would still like to handle that in a separate PR and not have those changes rolled into this one, if possible. I think it's better all-round if PRs stay as focussed on one thing, and don't try to cover too much. I will do this soon (some time this week) and roll into a release along with this and some other things I'm working on.

**Comment by bloodywing** [comment]
Okay @ababic added a revert and it just contains the locales now.

**Comment by ababic** [comment]
Brilliant. Thanks again @bloodywing. Merged now :)

**Pull request merged**
