### PR TITLE
python 2.7 compatibility

### PR DESCRIPTION
**Pull request by swamp-scout**
added unicode support for python 2.7

### CODE REVIEW

**Comment by ababic** [comment]
Hi @swamp-scout. Thanks for the contribution. Have you identified a need for this? Only, I've developed wagtailmenus primarily in a 2.7 environment and never had a problem. I'm guessing it's one of those things that only crops up when using non-english/ascii unicode strings?

**Comment by swamp-scout** [comment]
wagtailadmin raises UnicodeDecode exception when self.title is non-english unicode string (russian in my case)

**Comment by ababic** [comment]
Any chance you could add some tests for this to show a few views working with the non-english unicode strings in place?

**Comment by swamp-scout** [comment]
This case is described in the documentation:
https://docs.djangoproject.com/en/1.10/ref/utils/#module-django.utils.encoding
Additionally, this pattern successfully used in wagtail package without any issues

**Comment by ababic** [comment]
Okay, I get that. I'm sure it does work, and that we can trust well-documented Django code. I'm more concerned about functionality tests... that things work with these changes in place. It's less about testing what you've done, and more about ensuring that when changes are committed in future, those changes don't break compatibility somehow.

**Comment by ababic** [comment]
Hi @swamp-scout, I'd like to be able to get this feature in for a 1.5.2 release next week, but the pull still requires some simple tests. Just creating some FlatMenu instances (without menu items) with non-english unicode titles and testing that the list page doesn't raise errors will suffice.

Also, I'd like to avoid adding further migrations just for the sake of adding verbose names. Would you instead be able to doctor the existing migrations to add the verbose names, so an additional migration isn't needed?

Don't forget to add entries to CHANGELOG.md and CONTRIBUTORS.md and give yourself credit for your work, too :)

Let me know if there are any problems.

**Comment by ababic** [comment]
Superseded by #71

**Pull request closed without merging**
